version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 'YourStrong0Passw0rd'
      ACCEPT_EULA: 'Y'
    volumes:
      - ./db/scripts:/scripts 
    ports:
      - 1433:1433
  
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    volumes:
      - ./web:/usr/share/node
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db